# Generated by Django 4.2.30 on 2026-04-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='메뉴명')),
                ('price', models.IntegerField(default=0, verbose_name='가격(원)')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지URL')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_available', models.BooleanField(default=True, verbose_name='판매중')),
                ('is_popular', models.BooleanField(default=False, verbose_name='인기메뉴')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drinks.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴 목록',
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('is_active', models.BooleanField(default=True, verbose_name='재직/참여중')),
            ],
            options={
                'verbose_name': '팀원',
                'verbose_name_plural': '팀원 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='투표 제목')),
                ('vote_date', models.DateField(verbose_name='티타임 날짜')),
                ('is_active', models.BooleanField(default=True, verbose_name='투표 진행중')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '투표 세션',
                'verbose_name_plural': '투표 세션 목록',
                'ordering': ['-vote_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='내용(옵션/댓글)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.teammember', verbose_name='작성자')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='drinks.votesession', verbose_name='투표 세션')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글 목록',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='drinks.menuitem', verbose_name='선택 메뉴')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='drinks.teammember', verbose_name='참여자')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='drinks.votesession', verbose_name='투표 세션')),
            ],
            options={
                'verbose_name': '투표',
                'verbose_name_plural': '투표 목록',
                'unique_together': {('session', 'participant')},
            },
        ),
    ]
