# Generated by Django 4.2.30 on 2026-07-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['brand', 'order', 'name'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리 목록'},
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.CharField(choices=[('compose', '컴포즈커피'), ('mega', '메가커피'), ('mammoth', '매머드익스프레스')], default='compose', max_length=20, verbose_name='브랜드'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('brand', 'name')},
        ),
    ]
