# Generated by Django 4.2.30 on 2026-07-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_alter_category_options_category_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesession',
            name='brand',
            field=models.CharField(choices=[('compose', '컴포즈커피'), ('mega', '메가커피'), ('mammoth', '매머드익스프레스')], default='compose', max_length=20, verbose_name='브랜드'),
        ),
    ]
