# Generated by Django 4.2.30 on 2026-09-16 01:17

from django.db import migrations, models
import django.db.models.deletion


def create_default_coffee_shop_and_migrate_data(apps, schema_editor):
    CoffeeShop = apps.get_model('drinks', 'CoffeeShop')
    Category = apps.get_model('drinks', 'Category')
    MenuItem = apps.get_model('drinks', 'MenuItem')
    VoteSession = apps.get_model('drinks', 'VoteSession')

    # 기본 커피점 생성 (컴포즈커피 신도림점)
    default_shop, created = CoffeeShop.objects.get_or_create(
        name='컴포즈커피',
        branch_name='신도림점',
        defaults={
            'website_url': 'https://composecoffee.com',
            'description': '기본 컴포즈커피 신도림점',
            'is_active': True
        }
    )

    # 기존 Category 데이터 마이그레이션
    Category.objects.filter(coffee_shop__isnull=True).update(coffee_shop=default_shop)

    # 기존 MenuItem 데이터 마이그레이션
    MenuItem.objects.filter(coffee_shop__isnull=True).update(coffee_shop=default_shop)

    # 기존 VoteSession 데이터 마이그레이션
    VoteSession.objects.filter(coffee_shop__isnull=True).update(coffee_shop=default_shop)


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_votesession_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='커피점 상호명')),
                ('branch_name', models.CharField(blank=True, max_length=100, verbose_name='지점명')),
                ('website_url', models.URLField(blank=True, verbose_name='웹사이트 URL')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '커피점',
                'verbose_name_plural': '커피점 목록',
                'ordering': ['name', 'branch_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['coffee_shop', 'order', 'name'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리 목록'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['coffee_shop', 'category__order', 'name'], 'verbose_name': '메뉴', 'verbose_name_plural': '메뉴 목록'},
        ),
        migrations.RemoveField(
            model_name='votesession',
            name='brand',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='coffee_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='drinks.coffeeshop', verbose_name='커피점'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='coffee_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='drinks.coffeeshop', verbose_name='커피점'),
        ),
        migrations.AddField(
            model_name='votesession',
            name='coffee_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_sessions', to='drinks.coffeeshop', verbose_name='커피점'),
        ),
        migrations.RunPython(create_default_coffee_shop_and_migrate_data, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('coffee_shop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('coffee_shop', 'name')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='brand',
        ),
    ]
