# Generated by Django 4.2.30 on 2026-09-16 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_coffeeshop_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='coffee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='drinks.coffeeshop', verbose_name='커피점'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='coffee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='drinks.coffeeshop', verbose_name='커피점'),
        ),
        migrations.AlterField(
            model_name='votesession',
            name='coffee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_sessions', to='drinks.coffeeshop', verbose_name='커피점'),
        ),
    ]
