web:
  image: harbor.softworksapp.cloud/ttime/repository:v1
  imagePullPolicy: Always # 로컬 테스트를 위해 변경
  port: 8000

postgres:
  image: postgres:15-alpine
  user: friday
  password: softworks
  db: compose_vote
  storageSize: 1Gi

# 관리자 계정 자동 생성 설정
superuser:
  username: friday
  email: friday@softworks.co.kr
  password: softworks

ingress:
  enabled: true # 로컬에선 false, 실서버에선 true로 덮어쓰기
  className: "nginx"
  host: "ttime.softworksapp.cloud"
