apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        command: [ "sh", "-c" ]
        args:
          - |
            echo "===== 1단계: 기존 마이그레이션 파일 초기화 ====="
            rm -f drinks/migrations/00*.py

            echo "===== 2단계: 마이그레이션 설계도 생성 ====="
            python manage.py makemigrations drinks

            echo "===== 3단계: DB 테이블 생성 ====="
            python manage.py migrate

        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.db }}
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: compose-vote-db
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
  - port: 5432
