apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
    spec:
      imagePullSecrets:
        - name: harbor-regcred
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z compose-vote-db 5432; do
                echo "DB 대기중..."
                sleep 2
              done
              echo "DB 연결 확인 완료!"

      containers:
        - name: django-web
          image: {{ .Values.web.image }}
          imagePullPolicy: {{ .Values.web.imagePullPolicy }}

          command: ["sh", "-c"]
          args:
            - |
              #echo "===== 1단계: 기존 마이그레이션 파일 초기화 ====="
              #rm -f drinks/migrations/00*.py

              #echo "===== 2단계: DB 설계도 생성 ====="
              #python manage.py makemigrations

              #echo "===== 3단계: DB 테이블 생성 ====="
              #python manage.py migrate

              #echo "===== 4단계: 메뉴 데이터 크롤링 ====="
              #python manage.py crawl_menu

              #echo "===== 5단계: 관리자 계정 자동 생성 ====="
              #DJANGO_SUPERUSER_PASSWORD={{ .Values.superuser.password }} \
              #python manage.py createsuperuser --noinput \
              #--username {{ .Values.superuser.username }} \
              #--email {{ .Values.superuser.email }} || true

              echo "===== 6단계: Django 웹 서버 기동 ====="
              python manage.py runserver 0.0.0.0:{{ .Values.web.port }}

          env:
            - name: POSTGRES_HOST
              value: compose-vote-db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}

          ports:
            - containerPort: {{ .Values.web.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-web
  ports:
    - port: 80
      targetPort: {{ .Values.web.port }}
